### ISSUE TITLE
bash: ./Setup.sh: No such file or directory

### ISSUE THREAD

**Issue by masterofdaemon** [wshearn/UE4Docker#2]
on Fedora 22 it doesn't work

**Comment by sceek** [comment]
I had problems with that to, could only get it to work on debian based distributions

**Comment by wshearn** [comment]
The cause is selinux. You need to run `chcon -Rt svirt_sandbox_file_t /path/to/unrealengine`

See type enforcement http://www.projectatomic.io/docs/docker-and-selinux/
